### PR TITLE
support for banners other than osu!std

### PR DESCRIPTION
**Pull request by Starwort**
idiot-proofed so that nothing can break, defaults to 0 (std)

### CODE REVIEW

**Comment by aerisDoesCodes** [comment]
o

**Comment by Starwort** [comment]
of course, this heavily relies on my ability to remember JS lmao
I think it's right though

**Comment by aerisDoesCodes** [comment]
maybe lol

**Comment by Immortalizd** [comment]
> this heavily relies on my ability to remember JS lmao

this is why you test the code ;)

**Comment by Starwort** [comment]
> this is why you test the code ;)
speaking of... #4

**Pull request merged**
